name: docker
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
         echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
         docker pull ghcr.io/liquidz/babashka-test:latest
      - name: build latest
        run: |
         docker build . -t ghcr.io/liquidz/babashka-test:latest --cache-from ghcr.io/liquidz/babashka-test:latest
         docker push ghcr.io/liquidz/babashka-test:latest
      - name: build for tag
        if: contains(github.ref, 'refs/tags/')
        run: |
         TAG_NAME=$(echo "${{ github.ref }}" | sed 's!refs/tags/!!')
         docker build . -t ghcr.io/liquidz/babashka-test:${TAG_NAME} --cache-from ghcr.io/liquidz/babashka-test:latest
         docker push ghcr.io/liquidz/babashka-test:${TAG_NAME}
