name: test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Babashka test
        uses: ./
        with:
          source-paths: 'test/src'
          test-paths: 'test/test'
          test-file-pattern: '_test.clj$'
